{"timestamp":"2025-10-05T10:34:16.923979Z","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager","filename":"manager.py","lineno":179}
{"timestamp":"2025-10-05T10:34:16.925654Z","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/retail_transaction.py","logger":"airflow.models.dagbag.DagBag","filename":"dagbag.py","lineno":593}
{"timestamp":"2025-10-05T10:34:16.946947Z","level":"warning","event":"The `airflow.operators.python.PythonOperator` attribute is deprecated. Please use `'airflow.providers.standard.operators.python.PythonOperator'`.","category":"DeprecatedImportWarning","filename":"/opt/airflow/dags/retail_transaction.py","lineno":5,"logger":"py.warnings"}
{"timestamp":"2025-10-05T10:34:16.996228Z","level":"info","event":"Task instance is in running state","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:16.997295Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:16.998036Z","level":"info","event":"Current task name:load_task","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:16.998829Z","level":"info","event":"Dag name:etl_retail_transactions_fix","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.055139Z","level":"error","event":"Task failed with exception","logger":"task","filename":"task_runner.py","lineno":994,"error_detail":[{"exc_type":"UndefinedTable","exc_value":"relation \"public.retail_transactions\" does not exist\nLINE 2:         INSERT INTO public.retail_transactions\n                            ^\n","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1307,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":416,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":82,"name":"run"},{"filename":"/opt/airflow/dags/retail_transaction.py","lineno":155,"name":"load"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py","lineno":1299,"name":"execute_values"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-10-05T10:34:17.075490Z","level":"info","event":"Task instance in failure state","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.076949Z","level":"info","event":"Task start","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.077997Z","level":"info","event":"Task:<Task(PythonOperator): load_task>","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.079059Z","level":"info","event":"Failure caused by relation \"public.retail_transactions\" does not exist","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.079875Z","level":"info","event":"LINE 2:         INSERT INTO public.retail_transactions","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.080632Z","level":"info","event":"                            ^","logger":"task.stdout"}
{"timestamp":"2025-10-05T10:34:17.081085Z","level":"info","event":"","logger":"task.stdout"}
